### ISSUE TITLE
ding-dong bot broken due to typo

### ISSUE THREAD

**Issue by ak5** [zixia/wechaty#5]
Hi,
yesterday I ran into this small typo.

https://github.com/ak5/wechaty/commit/e5eaa91403bf38db4ce33033540bf9ca00738aa3

Alex

**Comment by zixia** [comment]
yes, it's already fixed on my local git.

if you use wechaty, I'll strong suggest you to use NPM installer to install a published version.

```bash
$ npm install wechaty --save
```

because the published version I'll check carefully and make sure all the tests are passed.

Or if you checkout the master head on github, it will not guaranteed to run because I always push half work to git respo(I know it's not right, but I have to switch between laptop and desktop computers...)

and, thanks using wechaty. :)
